### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by krish1905** [parkjs814/parkjs814.github.io#3]
@parkjs814 This is not exactly an issue though could you please help me create a terminal like you did in your website? My website- techiek.me
I know it is not a great website... I am still working on it

**Comment by 64json** [comment]
Hi @TechieKrish, looking into https://github.com/parkjs814/parkjs814.github.io/blob/e48cae3c42b84eaee39898c060a17cda028d449e/js/script.js#L250 from line 250 to 637 might help.
